export const products = [
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone XL',
    price: 799,
    description: 'A large phone with one of the best screens',
    heding1: 'サンプルテキスト1',
    heding2: 'サンプルテキスト2',
    heding3: 'サンプルテキスト3',
    headingtext1:'サンプルテキスト1-1',
    headingtext2:'サンプルテキスト2-2',
    headingtext3:'サンプルテキスト3-3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Mini',
    price: 699,
    description: 'A great phone with one of the best cameras',
    heding1: 'サンプルテキスト1',
    heding2: 'サンプルテキスト2',
    heding3: 'サンプルテキスト3',
    headingtext1:'サンプルテキスト1-1',
    headingtext2:'サンプルテキスト2-2',
    headingtext3:'サンプルテキスト3-3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Standard',
    price: 299,
    description: '',
    heding1: 'サンプルテキスト1',
    heding2: 'サンプルテキスト2',
    heding3: 'サンプルテキスト3',
    headingtext1:'サンプルテキスト1-1',
    headingtext2:'サンプルテキスト2-2',
    headingtext3:'サンプルテキスト3-3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone SP',
    price: 299,
    description: '',
    heding1: 'サンプルテキスト1-1',
    heding2: 'サンプルテキスト2-2',
    heding3: 'サンプルテキスト3-3',
    headingtext1:'サンプルテキスト1-1',
    headingtext2:'サンプルテキスト2-2',
    headingtext3:'サンプルテキスト3-3',
  }
];
